version: '3.8'

services:

  db1_for_users:
    image: postgres:13
    environment:
      POSTGRES_USER: ${USERS_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${USERS_DATABASE_PASSWORD}
      POSTGRES_DB: ${USERS_DATABASE_NAME}
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    networks:
      - app-network

  db2_for_messages:
    image: postgres:13
    environment:
      POSTGRES_USER: ${MESSAGES_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${MESSAGES_DATABASE_PASSWORD}
      POSTGRES_DB: ${MESSAGES_DATABASE_NAME}
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    networks:
      - app-network

  users:
    build:
      context: ./users
    environment:
      USERS_DATABASE_USERNAME: ${USERS_DATABASE_USERNAME}
      USERS_DATABASE_PASSWORD: ${USERS_DATABASE_PASSWORD}
      USERS_DATABASE_HOST: ${USERS_DATABASE_HOST}
      USERS_DATABASE_PORT: ${USERS_DATABASE_PORT}
      USERS_DATABASE_NAME: ${USERS_DATABASE_NAME}
    networks:
      - app-network
    volumes:
      - shared_data:/shared_data
    ports:
      - "8001:8000"

  messages:
    build:
      context: ./messages
    environment:
      MESSAGES_DATABASE_USERNAME: ${MESSAGES_DATABASE_USERNAME}
      MESSAGES_DATABASE_PASSWORD: ${MESSAGES_DATABASE_PASSWORD}
      MESSAGES_DATABASE_HOST: ${MESSAGES_DATABASE_HOST}
      MESSAGES_DATABASE_PORT: ${MESSAGES_DATABASE_PORT}
      MESSAGES_DATABASE_NAME: ${MESSAGES_DATABASE_NAME}
    networks:
      - app-network
    volumes:
      - shared_data:/shared_data
    ports:
      - "8002:8000"

  auth:
    build:
      context: ./auth
    networks:
      - app-network
    volumes:
      - shared_data:/shared_data
    ports:
      - "8003:8000"

  # Nginx веб-сервер
  nginx:
    image: nginx:latest
    volumes:
      - ./Frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - users
      - messages
      - auth
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data1:
  postgres_data2:
  shared_data:
